ALTER TABLE users
DROP COLUMN address;

ALTER TABLE users
    ADD address NVARCHAR(255) NULL;

ALTER TABLE tickets
ALTER COLUMN address NVARCHAR(255) NULL;

ALTER TABLE tickets
ALTER COLUMN reason NVARCHAR(500) NULL;

